workflow:
  rules:
    - when: always

stages:
  - test
  - deploy

####################
# Go tests (No Docker needed here)
####################
test:
  stage: test
  image: golang:1.26rc3-alpine3.23
  variables:
    IMAGE: "$CI_REGISTRY/$CI_PROJECT_PATH"
  tags:
    - golang
  script:
    - cd src
    - go test ./...

####################
# Build & Deploy
####################
deploy:
  stage: deploy
  image: docker:latest
  tags:
    - docker
  variables:
    IMAGE: "$CI_REGISTRY/$CI_PROJECT_PATH"
  before_script:
    # - mkdir -p /etc/docker/certs.d/registry.home2.lan
    # - echo "$CA_CERTIFICATE" > /etc/docker/certs.d/registry.home2.lan/ca.crt
    # - cp /etc/docker/certs.d/registry.home2.lan/ca.crt /usr/local/share/ca-certificates/ca.crt
    # - update-ca-certificates
    - echo $CI_REGISTRY_PASSWORD | docker login -u mahopon --password-stdin $CI_REGISTRY
  script:
    - docker build -t smolearl .
    - docker tag smolearl $IMAGE:$CI_COMMIT_SHA $IMAGE:latest
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker tag smolearl $IMAGE:latest
    - docker push $IMAGE:latest
  only:
    - main